In [1]:
import numpy as np

In [2]:
x=[[1,2,3],[3,2,7],[4,3,1]]

In [3]:
ar=np.array(x)

In [4]:
ar

array([[1, 2, 3],
       [3, 2, 7],
       [4, 3, 1]])

In [5]:
ar.sum(axis=0)

array([ 8,  7, 11])

In [6]:
ar.sum(axis=1)

array([ 6, 12,  8])

In [7]:
ar.T

array([[1, 3, 4],
       [2, 2, 3],
       [3, 7, 1]])

In [9]:
ar.flat

In [11]:
for item in  ar.flat:
    print(item)

1
2
3
3
2
7
4
3
1


In [12]:
ar.ndim

2

In [13]:
ar.size

9

In [14]:
ar.nbytes

72

In [20]:
one=np.array([1,3,4,87,98,4,9,56])

In [21]:
one.argmax()

np.int64(4)

In [22]:
one.argmin()

np.int64(0)

In [23]:
one.argsort()

array([0, 1, 2, 5, 6, 7, 3, 4])

In [24]:
ar

array([[1, 2, 3],
       [3, 2, 7],
       [4, 3, 1]])

In [25]:
ar.argmin()

np.int64(0)

In [26]:
ar.argmax()

np.int64(5)

In [27]:
ar.argmax(axis=0)

array([2, 2, 1])

In [28]:
ar.argmax(axis=1)  

array([2, 2, 0])

In [29]:
ar.argsort()

array([[0, 1, 2],
       [1, 0, 2],
       [2, 1, 0]])

In [30]:
ar.argsort(axis=0)

array([[0, 0, 2],
       [1, 1, 0],
       [2, 2, 1]])

In [31]:
ar.argsort(axis=1)

array([[0, 1, 2],
       [1, 0, 2],
       [2, 1, 0]])

In [32]:
ar.ravel()

array([1, 2, 3, 3, 2, 7, 4, 3, 1])

In [34]:
ar.reshape((9,1))

array([[1],
       [2],
       [3],
       [3],
       [2],
       [7],
       [4],
       [3],
       [1]])

In [35]:
ar

array([[1, 2, 3],
       [3, 2, 7],
       [4, 3, 1]])

In [36]:
   ar2=np.array([[1,3,4],[8,9,0],[2,6,1]])

In [37]:
ar2

array([[1, 3, 4],
       [8, 9, 0],
       [2, 6, 1]])

In [38]:
ar+ar2

array([[ 2,  5,  7],
       [11, 11,  7],
       [ 6,  9,  2]])

In [39]:
ar*ar2

array([[ 1,  6, 12],
       [24, 18,  0],
       [ 8, 18,  1]])

In [40]:
 np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081],
       [1.73205081, 1.41421356, 2.64575131],
       [2.        , 1.73205081, 1.        ]])

In [41]:
ar.sum()

np.int64(26)

In [42]:
ar.max()

np.int64(7)

In [43]:
ar.min()

np.int64(1)

In [44]:
np.where(ar>5)

(array([1]), array([2]))

In [45]:
ar

array([[1, 2, 3],
       [3, 2, 7],
       [4, 3, 1]])

In [46]:
 np.where(ar>2)

(array([0, 1, 1, 2, 2]), array([2, 0, 2, 0, 1]))

In [47]:
 np.count_nonzero(ar)

9

In [48]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 1, 2, 2, 2]), array([0, 1, 2, 0, 1, 2, 0, 1, 2]))

In [49]:
import sys

In [50]:
py_ar=[0,4,55,2]

In [51]:
np_ar=np.array(py_ar)

In [52]:
sys.getsizeof(1)*len(py_ar)

112

In [54]:
np_ar.itemsize*np_ar.size

32