# WELCOME TO NUMPY

In [23]:
 import numpy as np

In [2]:
myarr=np.array([3,4,6,9,10])

In [3]:
myarr

array([ 3,  4,  6,  9, 10])

In [4]:
myar=np.array([3,44555546,6,9,10],np.int8)

OverflowError: Python integer 44555546 out of bounds for int8

In [5]:
myarrr=np.array([3,44555546,6,9,10],np.int64)

In [6]:
myarrr

array([       3, 44555546,        6,        9,       10])

In [7]:
myarrrr=np.array([3,4,6,9,10])

In [8]:
myarrrr[0,1]

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

In [9]:
myarrrrr=np.array([[3,4,6,9,10]], np.int8)

In [10]:
myarrrrr[0,1]

np.int8(4)

In [11]:
myarrrrr.dtype

dtype('int8')

In [12]:
myarrrrr[0,1]=76

In [13]:
myarrrrr

array([[ 3, 76,  6,  9, 10]], dtype=int8)

# Array Creation : Conversion from other Python structures (e.g., lists, tuples)

In [14]:
listarray= np.array ([[1,2,3],[3,4,5],[5,8,0]])

In [15]:
listarray

array([[1, 2, 3],
       [3, 4, 5],
       [5, 8, 0]])

In [16]:
listarray.shape

(3, 3)

In [17]:
listarray.dtype

dtype('int64')

In [18]:
listarray.shape

(3, 3)

In [19]:
listarray.size

9

# Intrinsic numpy array creation objects (e.g., arange, ones, zeros, etc.)

In [24]:
zeros = np.zeros((3, 5))

In [25]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [27]:
rng=np.arange(15)

In [28]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [29]:
lspace=np.linspace(1,6,14)

In [30]:
lspace

array([1.        , 1.38461538, 1.76923077, 2.15384615, 2.53846154,
       2.92307692, 3.30769231, 3.69230769, 4.07692308, 4.46153846,
       4.84615385, 5.23076923, 5.61538462, 6.        ])

In [31]:
emp=np.empty((4,6))

In [32]:
emp

array([[6.77482612e-312, 7.70742408e-322, 0.00000000e+000,
        0.00000000e+000, 6.23053614e-307, 1.15998412e-028],
       [4.31603868e-080, 1.94919985e-153, 1.35717430e+131,
        7.06652016e-096, 7.06652016e-096, 1.81148490e-152],
       [9.37041222e-076, 6.98345624e-077, 6.98345624e-077,
        6.01391519e-154, 7.06673073e-096, 7.06652016e-096],
       [7.18988929e+140, 4.99874708e+217, 4.47303447e-143,
        1.46899974e+179, 9.08367237e+223, 1.16466228e-028]])

In [33]:
 emp_like=np.empty_like(lspace)

In [34]:
emp_like

array([1.        , 1.38461538, 1.76923077, 2.15384615, 2.53846154,
       2.92307692, 3.30769231, 3.69230769, 4.07692308, 4.46153846,
       4.84615385, 5.23076923, 5.61538462, 6.        ])

In [35]:
ide=np.identity(45)

In [36]:
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [37]:
arr=np.arange(45)

In [38]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44])

In [40]:
arr.reshape(3,15)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44]])

In [41]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44])

In [42]:
arr=arr.reshape(3,15)

In [43]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44]])

In [44]:
arr=arr.ravel()

In [45]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44])